# Generated by Django 5.2.7 on 2025-10-21 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentoAPP', '0001_initial'),
        ('inventarioAPP', '0001_initial'),
        ('proveedorAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('TRANSFERENCIA', 'Transferencia'), ('SALIDA', 'Salida')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('departamento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='departamentoAPP.departamento')),
                ('departamento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='departamentoAPP.departamento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarioAPP.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedorAPP.proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='StockActual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentoAPP.departamento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarioAPP.producto')),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'verbose_name_plural': 'Stock Actual',
                'unique_together': {('producto', 'departamento')},
            },
        ),
    ]
