# Generated by Django 5.2.7 on 2025-10-27 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentoAPP', '0001_initial'),
        ('movimientoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='costo_unitario_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario (Bs.)'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Factura/Referencia'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tasa_cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa de Cambio (Bs./USD)'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad (Paquetes)'),
        ),
        migrations.AlterField(
            model_name='stockactual',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='departamentoAPP.departamento'),
        ),
    ]
