# Generated by Django 5.2.7 on 2025-10-27 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoAPP', '0002_movimiento_costo_unitario_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser mayor a cero.')]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tasa_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tasa de Cambio (Bs./USD)'),
        ),
        migrations.AlterField(
            model_name='stockactual',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
