# Generated by Django 5.2.7 on 2025-10-27 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoAPP', '0003_alter_movimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad (Paquetes)'),
        ),
        migrations.AlterField(
            model_name='stockactual',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
