# Generated by Django 5.2.7 on 2025-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoAPP', '0004_alter_movimiento_cantidad_alter_stockactual_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='costo_unitario_bs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario por paq(Bs.)'),
        ),
    ]
