# Generated by Django 5.2.7 on 2025-11-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoAPP', '0006_movimiento_usuario_registra'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='costo_unitario_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Costo Unitario (USD) / Unidad'),
        ),
    ]
