# Generated by Django 5.2.7 on 2025-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientoAPP', '0007_movimiento_costo_unitario_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockactual',
            name='costo_maximo_vigente',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Costo Más Alto en Stock (USD)'),
        ),
    ]
