# Generated by Django 5.2.7 on 2025-10-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentoAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='encargado',
        ),
        migrations.DeleteModel(
            name='Encargado',
        ),
    ]
