# Generated by Django 5.2.7 on 2025-10-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedorAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='ruc',
            new_name='rif',
        ),
    ]
