# Generated by Django 5.2.7 on 2025-10-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentoAPP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador General'), ('GERENTE', 'Gerente de Departamento'), ('OPERADOR', 'Operador de Departamento')], default='OPERADOR', max_length=10)),
                ('departamento', models.ForeignKey(blank=True, help_text='Departamento al que pertenece el usuario (si no es Admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentoAPP.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
