# Generated by Django 5.2.7 on 2025-11-01 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentoAPP', '0002_remove_departamento_encargado_delete_encargado'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento al que pertenece el usuario (si no es Admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='departamentoAPP.departamento'),
        ),
    ]
