# Generated by Django 5.2.7 on 2025-10-22 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0002_remove_categoria_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='La unidad de medida debe ser mayor que 0.')], verbose_name='Cantidad por Unidad'),
        ),
    ]
