# Generated by Django 5.2.7 on 2025-11-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0003_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Stock Mínimo (Paquetes)'),
        ),
    ]
